[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "detikzify"
readme = "README.md"
license = {text = "Apache-2.0 License"}
dependencies = [
  "torch~=2.1",
  "transformers~=4.36",
  "diffusers~=0.24",
  "tokenizers~=0.15",
  "datasets~=2.15",
  "timm~=0.9",
  "Pillow~=10.1",
  "requests~=2.31",
  # pdf
  "PyMuPDF~=1.23",
  "pdf2image~=1.16",
  "pdfCropMargins~=2.0",
  # webui
  "gradio~=4.13",
  # evaluate
  "POT~=0.9",
]
requires-python = "~=3.10"
dynamic = ["version"]

[project.optional-dependencies]
evaluate= [
  "torchmetrics~=1.3",
  "Pygments~=2.17",
  "crystalbleu~=0.1",
  "sacremoses~=0.1"
]
deepspeed = [
  "deepspeed~=0.12"
]

[project.urls]
repository = "https://github.com/potamides/DeTikZify"

[tool.setuptools_scm]
write_to = "detikzify/_version.py"
parentdir_prefix_version = "detikzify-"

[tool.setuptools.packages.find]
include = ["detikzify*"]
